---
title: "Storms"
output: html_document
---
```{r, warning=FALSE, message=FALSE}
library(tidyverse)

mystorms <- read_tsv("../R/data_storms.tsv")

mystorms %>% head()
```

```{r}
mystorms %>%
  filter(year < 1990, category >= 3) %>%
  group_by(month) %>%
  summarise(`Days.of.3+.Storms.Before.1990`=n()/4)
```



```{r}
mystorms %>%
  filter(year >= 1990, category >= 3) %>%
  group_by(month) %>%
  summarise(`Days.of.3+.Storms.After.1990`=n()/4)
```

```{r}
mystorms %>%
  group_by(year) %>%
  summarise(median_pressure = median(pressure),
            delta_pressure = max(pressure) - min(pressure))
```

```{r}
mystorms %>%
  group_by(year,name) %>%
  filter(status == "hurricane") %>%
  summarise(mean.pressure = mean(pressure),
            median.pressure = median(pressure))
```


```{r}
mystorms %>%
  group_by(year,status) %>%
  summarise(unique_storms = n_distinct(name))
```

```{r}
month.to.days <-
  function (x){
    days_in_month = list(
      "1" = 31,
      "2" = 28,
      "3" = 31,
      "4" = 30,
      "5" = 31,
      "6" = 30,
      "7" = 31,
      "8" = 31,
      "9" = 30,
      "10" = 31,
      "11" = 30,
      "12" = 31)
    ret_val <- days_in_month[x]
    return(unlist(ret_val))
  }
mystorms %>%
  group_by(year) %>%
  filter(category >= 4) %>%
  summarise(storm.count = n_distinct(name),
            mean_month = mean(month+day/month.to.days(month)+hour/24))


```

